theme:
  activeBorderColor:
    - '#7aa2f7'
    - bold
  inactiveBorderColor:
    - '#565f89'
  optionsTextColor:
    - '#bb9af7'
  selectedLineBgColor:
    - '#292e42'
  cherryPickedCommitBgColor:
    - '#3b4261'
  cherryPickedCommitFgColor:
    - '#7aa2f7'
  unstagedChangesColor:
    - '#f7768e'
  defaultFgColor:
    - '#c0caf5'
  searchingActiveBorderColor:
    - '#e0af68'

authorColors:
  '*': '#7aa2f7'
